# Site settings
title: "My Quest"
name: "Sarwangi Patel"
description: "Exploring physics and ideas."
url: "https://sarwangipatel.github.io" # Your live site URL

# Author info (appears in sidebar if enabled)
author:
  name: "Sarwangi Patel"
  bio: "Researcher, writer, and explorer of ideas."
  location: "India"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/SarwangiPatel"

# Theme (GitHub Pages-compatible)
theme: minimal-mistakes-jekyll

# Optional visual style
minimal_mistakes_skin: "default" # Try "air", "mint", "sunrise", "dark", etc.

# Build settings
markdown: kramdown
highlighter: rouge

# Navigation bar
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: /about/
  - title: "Blog"
    url: /blog/

# Include custom pages folder
include:
  - _pages

# Collections (for portfolio use)
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

# Pagination (optional for blog posts)
paginate: 5
paginate_path: /page:num/

# Output options
permalink: /:title/
