# Site Settings
title: "My Quest"
name: "Sarwangi Patel"
description: "..."
url: "https://SarwangiPatel.github.io"

# Author Info (appears in sidebar)
author:
  name: "Sarwangi Patel"
  bio: ""
  location: ""
  links: []

# Site Configuration
repository: "SarwangiPatel/SarwangiPatel.github.io"
masthead_title: "Sarwangi Patel"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # Options: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Navigation (basic structure — feel free to expand later)
include:
  - _pages

# Pagination
paginate: 5
paginate_path: /page:num/

# Collections (for future portfolio use)
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/
