title: "Sarwangi Patel"
description: "Theoretical Physics Research"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

author:
  name: "Sarwangi Patel"
  bio: "Physics Researcher"

plugins:
  - jekyll-include-cache
